export { default as Home } from './Home/Home'
export { default as Speakers } from './Speakers/Speakers'
export { default as Headphones } from './Headphones/Headphones'
export { default as Earphones } from './Earphones/Earphones'
export { default as ProductDetail } from './ProductDetail/ProductDetail'
